-- MySQL Script generated by MySQL Workbench
-- Mon Dec  6 23:53:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auth` (
  `idAuth` INT NOT NULL AUTO_INCREMENT,
  `login` LONGTEXT NOT NULL,
  `pass` LONGTEXT NOT NULL,
  PRIMARY KEY (`idAuth`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `surname` LONGTEXT NOT NULL,
  `birthdate` DATE NOT NULL,
  `email` LONGTEXT NOT NULL,
  `Auth_idAuth` INT NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `idWarehouse` INT NOT NULL AUTO_INCREMENT,
  `availability` TINYINT NOT NULL,
  PRIMARY KEY (`idWarehouse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bookstore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bookstore` (
  `idBookstore` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `author` LONGTEXT NOT NULL,
  `isbn` LONGTEXT NOT NULL,
  `publishingHouse` LONGTEXT NOT NULL,
  `releaseDate` DATE NOT NULL,
  `Warehouse_idWarehouse` INT NOT NULL,
  PRIMARY KEY (`idBookstore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `dateOfOrder` DATE NOT NULL,
  `dateOfReceive` DATE NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `Bookstore_idBookstore` INT NOT NULL,
  PRIMARY KEY (`idOrders`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bookstore_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bookstore_copy1` (
  `idBookstore` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `author` LONGTEXT NOT NULL,
  `isbn` LONGTEXT NOT NULL,
  `publishingHouse` LONGTEXT NOT NULL,
  `releaseDate` DATE NOT NULL,
  `Warehouse_idWarehouse` INT NOT NULL,
  PRIMARY KEY (`idBookstore`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
